version : "3"
services: 
  api:
    depends_on:
      - postgres
    build: .
    ports:
      - 40000:8000
    volumes:
      - .:/usr/src/app:ro
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=power123#
      - DATABASE_NAME=FastAPI
      - SECRET_KEY=HelloForTheSecret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      
     
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=power123#
      - POSTGRES_DB=FastAPI
    
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
