name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: TestEnv
    env: 
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password123
      DATABASE_NAME: FastAPI
      SECRET_KEY: HelloForSecret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: FastAPI_test
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 



    runs-on: ubuntu-latest
    steps:
      - name: pulling get repo
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
      
      - name: install all dependencies
        run: pip install -r requirements.txt

      - name: Test Code
        run: pytest -v -s
      


           
    
  